config/routes.rb
Rails.application.routes.draw do
  get 'invitation/create'
  get 'invitation/destroy'
  get 'attendance/create'
  resources :events
  get 'session/new'
  delete 'session/destroy'
  post 'session/log_in'
  resources :users
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  validates_uniqueness_of :attendee_id, scope: [:event_id]

  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :attendance, foreign_key: :event_id
  has_many :attendees, through: :attendance, source: :attendee
  has_many :invitation, foreign_key: :event_id
  has_many :invitees, through: :invitation, source: :invitee

  validates :description, presence: true
  validates :date, presence: true
  validates :creator, presence: true
  scope :past_events, -> { where('date < ?', Time.now) }
  scope :upcoming_events, -> { where('date >= ?', Time.now) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  validates_uniqueness_of :invitee_id, scope: [:event_id]

  belongs_to :invitee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true

  has_many :events, foreign_key: :creator_id
  has_many :attendance, foreign_key: :attendee_id
  has_many :attended_events, through: :attendance, source: :event
  has_many :invitation, foreign_key: :invitee_id
  has_many :invited_events, through: :invitation, source: :event

  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  before_action :signed_in?, only: [:create]

  def create
    @attendance = Attendance.new
    @attendance.attendee_id = session[:user_id]
    @attendance.event_id = params[:event]
    if @attendance.save
      if params[:invitation]
        redirect_to invitation_destroy_path(id: params[:invitation], event: params[:event])
      else
        redirect_to event_path(params[:event])
      end
    else
      flash.alert = 'Unable To Join'
      redirect_to event_path(params[:event])
    end
  end

  def signed_in?
    return true if session[:user_id] && session[:user_name]

    redirect_to session_new_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :signed_in?, only: [:new]

  # GET /events
  # GET /events.json
  def index
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @users = User.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # POST /events
  # POST /events.json
  def create
    @event = User.find(session[:user_id]).events.build(event_params)

    if @event.save
      flash.notice = 'Event was successfully created.'
      redirect_to @event
    else
      errors = @event.errors.map(&:full_message)
      flash.alert = errors.join('<br/>').html_safe
      render :new
    end
  end

  def signed_in?
    return true if session[:user_id] && session[:user_name]

    redirect_to session_new_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:description, :date, :creator_id)
  end
end

app/controllers/invitation_controller.rb
class InvitationController < ApplicationController
  before_action :signed_in?, only: [:create]

  def create
    @invitation = Invitation.new
    @invitation.event_id = params[:event]
    @invitation.invitee_id = params[:user]
    @invitation.save ? flash.notice = 'Invitation Sent Successfully' : flash.alert = 'Invitation Not Sent'
    redirect_to event_path(params[:event])
  end

  def destroy
    Invitation.destroy(params[:id])
    flash.notice = 'Success!'
    redirect_to event_path(params[:event])
  end

  def signed_in?
    return true if session[:user_id] && session[:user_name]

    redirect_to session_new_path
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    @user = User.new
  end

  def log_in
    result = User.where(name: params[:user][:name])
    if result.empty?
      flash[:alert] = 'User not found.'
      redirect_to session_new_path
    else
      user = result.first
      session[:user_id] = user[:id]
      session[:user_name] = user[:name]
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @created_events = @user.events
    @invited_events = @user.invited_events
    @past_events = @user.attended_events.past_events
    @upcoming_events = @user.attended_events.upcoming_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:user_name] = @user.name
      flash.notice = 'User was successfully created.'
      redirect_to @user
    else
      errors = @user.errors.map(&:full_message)
      flash.alert = errors.join('<br/>').html_safe
      # redirect_to new_user_path
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_helper.rb
module AttendanceHelper
end

app/helpers/events_helper.rb
module EventsHelper
  # checks if the user current user is already attending meeting
  def invalid_invitee?(user)
    user.id == @event.creator_id || @event.attendees.include?(user) || @event.invitees.include?(user)
  end

  def user_invited?
    @event.invitee_ids.include?(session[:user_id])
  end

  def user_not_attending?
    !@event.attendee_ids.include?(session[:user_id])
  end

  def show_more_to_invite?
    @event.attendees.count + @event.invitees.count + 1 != @users.count && @event.creator_id == session[:user_id]
  end
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendance/create.html.erb
<h1>Attendance#create</h1>
<p>Find me in app/views/attendance/create.html.erb</p>

app/views/events/_event.html.erb
<div class="content margin8 event">
  <h2><%= event.description %></h2>
  <div class="text_red"><%= event.date %></div>
  <div class="capitalise italic">Creator: <%= User.find(event.creator_id).name %></div>
  <div><%= link_to 'Show', event, class: "links margin8" %></div>
</div>

app/views/events/_form.html.erb
<div class="col margin8">
  <%= form_with(model: event, class: "form") do |form| %>
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="field">
      <%= form.label :date %>
      <%= form.datetime_select :date %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/events/index.html.erb
<h1 class="page_title">Events</h1>

<div class="col">
  <span class="heading">Past Events</span>
  <div class="row wrap">
    <% @past_events.each do |event| %>
      <%= render 'event', event: event %>
    <% end %>
  </div>

  <span class="heading">Upcoming Events</span>
  <div class="row wrap">
    <% @upcoming_events.each do |event| %>
      <%= render 'event', event: event %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1 class="page_title margin8 row main-center">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class: "links margin8"%>

app/views/events/show.html.erb
<div class="col">
  <div class="content margin8">
    <p>
      <h2><%= @event.description %></h2>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Creator:</strong>
      <%= @event.creator.name %>
    </p>

    <p>
      <strong>Attendees:</strong>
      <% @event.attendees.each do |attendee| %>
        <p><%= attendee.name %></p>
      <% end %>
    </p>

    <p>
      <strong>Invitees:</strong>
      <% @event.invitees.each do |invitee| %>
        <p><%= invitee.name %></p>
      <% end %>
    </p>
  </div>

  <% if user_invited? %>
    <div class="row layout-margin8 attend">
      <%= link_to 'Accept Invitation', :controller => 'attendance', :action => 'create', :event => @event, :invitation => @event.invitation.where(invitee_id: session[:user_id], event_id: @event.id).first %>
      <%= link_to 'Decline Invitation', :controller => 'invitation', :action => 'destroy', :event => @event, :id => @event.invitation.where(invitee_id: session[:user_id], event_id: @event.id).first %>
    </div>
  <% elsif user_not_attending? %>
    <div class="row layout-margin8 attend">
      <%= link_to 'Attend', :controller => 'attendance', :action => 'create', :event => @event %>
    </div>
  <% end %>

  <% if show_more_to_invite? %>
    <div class="col content margin8 ">
      <strong>Invitations</strong>
      <% @users.each do |user| %>
        <%  unless invalid_invitee?(user) %>
          <div class="row margin8 invitation-item">
            <div class="margin8 row cross-center w-25"> <%= user.name %> </div>
            <%= link_to 'Invite', class: "links margin8", :controller => 'invitation', :action => 'create', :event => @event, :user => user %>
          </div>
        <%  end %>
      <% end %>
    </div>
  <%end%>
</div>

app/views/invitation/create.html.erb
<h1>Invitation#create</h1>
<p>Find me in app/views/invitation/create.html.erb</p>

app/views/invitation/destroy.html.erb
<h1>Invitation#destroy</h1>
<p>Find me in app/views/invitation/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <nav class="nav row">
      <div class="row">
          <%= link_to "Home", root_path, class: "nav_item" %>
          <%= link_to 'New Event', new_event_path, class: "nav_item"%>
      </div>
      <% if session[:user_id] %>
        <div class="row">
          <%= link_to session[:user_name], user_path(session[:user_id]), class: "nav_item" %>
          <%= link_to "Log Out", session_destroy_path(1), method: :delete, class: "nav_item" %>
        </div>
      <% else %>
        <div class="row">
          <%= link_to 'Log In', session_new_path, class: "nav_item" %>
          <%= link_to 'Sign Up', new_user_path, class: "nav_item" %>
          </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/session/_form.html.erb
<%= form_for @user, :html => {:class => 'form'}, :url => { :action => "log_in" } do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit 'Log In' %>
  </div>
<% end %>

app/views/session/new.html.erb
<h1 class="page_title">Log In</h1>

<%= render 'form', user: @user %>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "form") do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 class="page_title">Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user , class: "links"%></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "links" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "links" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, class: "links" %>

app/views/users/new.html.erb
<h1 class="page_title">New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<div class="col">
  <div class="content margin8">
    <h2 class="margin8 row main-center"><%= @user.name%></h2>

    <div class="col margin8">
      <strong class="heading">Events Created:</strong>
      <div class="row wrap">
        <% @created_events.each do |event| %>
          <%= render 'events/event', event: event %>
        <% end %>
      </div>
    </div>

    <div class="col margin8">
      <strong class="heading">Events Invited:</strong>
      <div class="row wrap">
        <% @invited_events.each do |event| %>
          <%= render 'events/event', event: event %>
        <% end %>
      </div>
    </div>

    <div class="col margin8">
      <strong class="heading">Upcoming Events to attend:</strong>
      <div class="row wrap">
        <% @upcoming_events.each do |event| %>
          <%= render 'events/event', event: event %>
        <% end %>
      </div>
    </div>

    <div class="col margin8">
      <strong class="heading">Previously attended Events:</strong>
      <div class="row wrap">
        <% @past_events.each do |event| %>
          <%= render 'events/event', event: event %>
        <% end %>
      </div>
    </div>
  </div>
</div>